"""add gender column to user

Revision ID: 8325aa0fd616
Revises: cf65d953d9b5
Create Date: 2026-05-15 13:37:42.966850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8325aa0fd616'
down_revision: Union[str, Sequence[str], None] = 'cf65d953d9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_options_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_options_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_detail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('investment_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receipt_type', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('receipt_type')
        batch_op.drop_column('investment_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('source_detail')
        batch_op.drop_column('income_source')

    with op.batch_alter_table('income_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_options_id'))
        batch_op.drop_index(batch_op.f('ix_income_options_category'))

    op.drop_table('income_options')
    # ### end Alembic commands ###
